server:
  port: 9091
  # validation since spring boot 2.3
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank

security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey
